var availableTools = [
	{"name":"Soldering Iron"},
	{"name":"Philips 3.2 x 75mm Screwdriver"},
	{"name":"Philips 5.0 x 75mm Screwdriver"},
	{"name":"Philips 6.0 x 100mm Screwdriver"},
	{"name":"Slotted 5.0 x 75mm Screwdriver"},
	{"name":"Slotted 3.2 x 75mm Screwdriver"},
	{"name":"Electrical Test Screwdriver"},
	{"name":"Utility Knife"},
	{"name":"2-piece Alignment Tool Set"},
	{"name":"Solder Core"},
	{"name":"Desoldering Pump"},
	{"name":"Anti-Static Wrist Strap"},
	{"name":"8-piece Mini-electronic Combination Wrench Set"},
	{"name":"6-piece Precision Screwdriver Set"},
	{"name":"8in Wire Strip Pliers"},
	{"name":"5in Side Cutter Pliers"},
	{"name":"6in Long Nose Pliers"},
	{"name":"6in Lineman's Pliers"},
	{"name":"9in Coaxial Crimping Tool"},
	{"name":"Soldering Stand"},
	{"name":"Digital Multimeter"},
	{"name":"Hammer"},
	{"name":"Tweezers"},
	{"name":"Flashlight"},
	{"name":"Penlight"},
	{"name":"Socket Wrench"},
	{"name":"Bolts"},
	{"name":"Screws"},
	{"name":"Washers"},
	{"name":"Spring Hook"},
	{"name":"Boroscope"}
]

/*
	Statuses: Requested -> Shipped -> Received -> Used (Bolts, Washers, Screws ONLY) or Returned
*/
var jobs = [
	{"location":"Cincinnati",
	"date":"11/1/2015",
	"tools":[
		{"name":"Bolts",
		"status":"Used",
		"quantity":32},
		{"name":"Washers",
		"status":"Used",
		"quantity":32},
		{"name":"Screws",
		"status":"Used",
		"quantity":32},
		{"name":"Philips 5.0 x 75mm Screwdriver",
		"status":"Returned",
		"quantity":1},
		{"name":"6in Lineman's Pliers",
		"status":"Returned",
		"quantity":1},
		{"name":"Flashlight",
		"status":"Returned",
		"quantity":1}
	]},
	{"location":"New York",
	"date":"11/15/2015",
	"tools":[
		{"name":"Soldering Iron",
		"status":"Returned",
		"quantity":1},
		{"name":"Soldering Stand",
		"status":"Returned",
		"quantity":1},
		{"name":"Solder Core",
		"status":"Returned",
		"quantity":1},
		{"name":"2-piece Alignment Tool Set",
		"status":"Received",
		"quantity":1},
		{"name":"Desoldering Pump",
		"status":"Returned",
		"quantity":1},
		{"name":"Anti-Static Wrist Strap",
		"status":"Received",
		"quantity":1}
	]},
	{"location":"Detroit",
	"date":"11/29/2015",
	"tools":[
		{"name":"8-piece Mini-electronic Combination Wrench Set",
		"status":"Requested",
		"quantity":1},
		{"name":"6-piece Precision Screwdriver Set",
		"status":"Shipped",
		"quantity":1},
		{"name":"Screws",
		"status":"Shipped",
		"quantity":12},
		{"name":"6in Long Nose Pliers",
		"status":"Shipped",
		"quantity":1}
	]},
	{"location":"Chicago",
	"date":"12/13/2015",
	"tools":[
		{"name":"9in Coaxial Crimping Tool",
		"status":"Requested",
		"quantity":1},
		{"name":"8in Wire Strip Pliers",
		"status":"Requested",
		"quantity":1},
		{"name":"Utility Knife",
		"status":"Requested",
		"quantity":1},
		{"name":"Tweezers",
		"status":"Requested",
		"quantity":1},
		{"name":"5in Side Cutter Pliers",
		"status":"Requested",
		"quantity":1},
		{"name":"Anti-Static Wrist Strap",
		"status":"Requested",
		"quantity":1}
	]},
	{"location":"Pittsburgh",
	"date":"12/27/2015",
	"tools":[]},
	{"location":"Indianapolis",
	"date":"1/10/2016",
	"tools":[]}
]
